### ISSUE TITLE
build a library which should be compatible with the generated models

### ISSUE THREAD

**Issue by yorkie** [weflex/pancake#6]
Inspired by https://github.com/weflex/weflex/pull/53 (private repo pr).

Actually we were creating a client library, that we call it libgian that we are using to connect to the data, but the issue is when we would have a update about model, we have to update the client library as well, so that I think we should generate this library when building with pancake, then we are able to use that at:
1. as a dependency just like what we did for models directory.
2. serve the client library at the final server.

/cc @scottoasis @weflex/designers

**Comment by jkvim** [comment]
+1. interesting.

**Comment by yorkie** [comment]
Close because of weflex/pancake-sdk-javascript.
